name: test

on:
  workflow_dispatch:
  schedule:
    - cron: '30 23 * * *'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: 
          npm install axios
      - run:
          node test.js
